[build]
  publish = "."

[[redirects]]
  from = "/stay/patagonia-casa-calma/*"
  to = "/stay/argentina-casa-calma/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/stay/patagonia-casa-paz/*"
  to = "/stay/argentina-casa-paz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat/index.html"
  status = 200
  force = false
